Add crypto crate to the toolkit
enigmampc/secret-toolkit pull request #4
Opened 2020-11-08 19:24 UTC by PumpkinSeed

Based on the [I609](https://github.com/enigmampc/SecretNetwork/issues/609) I moved the original content to the crypto crate and make them public based on the pattern of the other crates.

Also changes on my side: 
- Added the verify function to the secp256k1.
- Add tests for all of the public functions. 

Leftover:
I didn't add **ed25519** signing however the original ticket contains it. This requires a decision on your part, since I found a [crate](https://docs.rs/ed25519/1.0.3/ed25519/) for that purpose, I would say do it in a different PR. 
Also to make it consistent, currently the sign.rs only support secp256k1, I don't know whether we can use the same parameter-set for ed25529, but if yes we can create an enum for decide between algorithms to sign the data. 

```
enum SignAlgorithm {
  Secp256k1
  Ed25519
}
```

2020-11-09 08:43 UTC, Cashmaney commented
Thanks @PumpkinSeed! @reuvenpo can you take a look and make sure everything is rusty?

2020-11-09 11:08 UTC, reuvenpo requested changes
You did not export the `crypto` subcrate from the main `secret_toolkit` namespace. I'll do it for you real quick

2020-11-09 11:08 UTC, reuvenpo commented on packages/crypto/src/sign.rs
> +        }
you can probably use `copy_from_slice` here instead of this `for` loop

2020-11-09 11:08 UTC, reuvenpo commented on packages/crypto/src/sign.rs
> +        }
you can probably use `copy_from_slice` here instead of this `for` loop

2020-11-09 11:53 UTC, reuvenpo commented on packages/crypto/src/sign.rs
> +        );
This can be simply:
```rust
assert!(verify(&data, signature, &secp_pubkey.serialize_uncompressed;
```

2020-11-10 12:19 UTC, reuvenpo approved these changes
awesome PR, thanks @PumpkinSeed :D

2020-11-10 12:20 UTC, merged